# https://travis-ci.org/pyschool/workshopper
sudo: false
os:
  - linux
  - osx
env:
  global:
    - NEWEST_PYTHON=3.4
language: python
python:
  - 3.3
  - 3.4
  - pypy3
script:
  - make
install:
  - travis_retry pip install coveralls
after_success:
  - coveralls
